let classes = [
  {
    name: "History",
    teacher: "Mr. Paul",
    hour: "2p.m - 3p.m",
    color: "#32a854",
    hasATest: true,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Social Studies",
    teacher: "Mrs. Carmen",
    hour: "8a.m - 9a.m",
    color: "#329ea8",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Antropology",
    teacher: "Mrs. Ana",
    hour: "10a.m - 11a.m",
    color: "#77a832",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["highschool"],
  },
  {
    name: "Math",
    teacher: "Mrs. Rosa",
    hour: "1p.m - 2p.m",
    color: "#de0d0d",
    hasATest: false,
    hasAwarning: true,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Physics",
    teacher: "Mr. Carl Paulson",
    hour: "2p.m - 3p.m",
    color: "#de0d0d",
    hasATest: false,
    hasAwarning: true,
    grade: 0,
    for: ["middle-school", "highschool"],
  },
  {
    name: "Chemistry",
    teacher: "Mr. Deutsch",
    hour: "5p.m - 6p.m",
    color: "#0d5ade",
    hasATest: false,
    hasAwarning: true,
    grade: 0,
    for: ["middle-school", "highschool"],
  },
  {
    name: "Biology",
    teacher: "Mr. Michael",
    hour: "3p.m - 4p.m",
    color: "#105e2e",
    hasATest: true,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Philosophy",
    teacher: "Mrs. Blakefield",
    hour: "3p.m - 4p.m",
    color: "#890aa8",
    hasATest: false,
    hasAwarning: true,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Ethics",
    teacher: "Mrs. Blakefield",
    hour: "5p.m - 6p.m",
    color: "#a80aa0",
    hasATest: false,
    hasAwarning: true,
    grade: 0,
    for: ["middle-school", "highschool"],
  },
  {
    name: "English",
    teacher: "Mrs. Amber",
    hour: "9a.m - 10a.m",
    color: "#5c0aa8",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Italian",
    teacher: "Mr. Paolo",
    hour: "11a.m - 12a.m",
    color: "#36e33f",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Portuguese",
    teacher: "Mr. Pereira",
    hour: "11a.m - 12a.m",
    color: "#cfbf0e",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "German",
    teacher: "Mrs. Volk",
    hour: "8a.m - 9a.m",
    color: "#cf880e",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Spanish",
    teacher: "Mrs. Carmen",
    hour: "9a.m - 10a.m",
    color: "#cf4b0e",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "French",
    teacher: "Mr. François",
    hour: "11a.m - 12a.m",
    color: "#0e4bcf",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["primary-school", "middle-school", "highschool"],
  },
  {
    name: "Computer Hardware I",
    teacher: "Mrs. French",
    hour: "8a.m - 9a.m",
    color: "#9fcf0e",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["middle-school", "highschool"],
  },
  {
    name: "Computer Hardware II",
    teacher: "Mrs. French",
    hour: "8a.m - 9a.m",
    color: "#9fcf0e",
    hasATest: false,
    hasAwarning: false,
    grade: 0,
    for: ["middle-school", "highschool"],
  },
];

export default classes;
