let teachers = [
  {
    name: "Mr. Paul",
    subject: "History",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Carmen",
    subject: "Social Studies",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Ana",
    subject: "Antropology",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Rosa",
    subject: "Math",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Carl Paulson",
    subject: "Physics",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Deutsch",
    subject: "Chemistry",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Michael",
    subject: "Biology",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Blakefield",
    subject: "Philosophy",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Blakefield",
    subject: "Ethics",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Amber",
    subject: "English",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Paolo",
    subject: "Italian",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Pereira",
    subject: "Portuguese",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Volk",
    subject: "German",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Carmen",
    subject: "Spanish",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. François",
    subject: "French",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. French",
    subject: "C. Hardware",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Carol",
    subject: "P.E",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. Java",
    subject: "Java",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. C",
    subject: "C#",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mrs. J",
    subject: "Javascript",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Pietro",
    subject: "HTML + CSS",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
  {
    name: "Mr. Pietro",
    subject: "Python",
    officeHours: "9a.m - 6p.m",
    phone: "(99)999-9999",
  },
];

export default teachers;
